export const DEFAULT_LAT = 52.23;

export const DEFAULT_LNG = 21.0111;

export const CANT_FIND_CITY =
  "If you can't find your city in the list, don't worry! You can still search for it.";

export const CANT_FIND_TYPE = "Please, choose one from types in list!";

export const FILTERS = [
  { id: 1, name: "Hospital" },
  { id: 2, name: "Police" },
  { id: 3, name: "Fire Station" },
  { id: 4, name: "Hotels" },
  { id: 5, name: "University" },
  { id: 6, name: "Secondary School" },
  { id: 7, name: "Primary School" },
  { id: 8, name: "Post Office" },
  { id: 9, name: "Department" },
  { id: 10, name: "Park" },
  { id: 11, name: "Museum" },
  { id: 12, name: "Movie Theater" },
  { id: 13, name: "Tourist Attraction" },
  { id: 14, name: "Gym" },
  { id: 15, name: "Restaurant" },
  { id: 16, name: "Cafe" },
  { id: 17, name: "Bar" },
  { id: 18, name: "Supermarket" },
  { id: 19, name: "Clothing Store" },
  { id: 20, name: "Department Store" },
  { id: 21, name: "Electronics Store" },
  { id: 22, name: "Shopping Mall" },
  { id: 23, name: "Library" },
];

export const CITIES = [
  { id: 1, name: "Warsaw" },
  { id: 2, name: "Kraków" },
  { id: 3, name: "Łódź" },
  { id: 4, name: "Wrocław" },
  { id: 5, name: "Poznań" },
  { id: 6, name: "Gdańsk" },
  { id: 7, name: "Szczecin" },
  { id: 8, name: "Bydgoszcz" },
  { id: 9, name: "Lublin" },
  { id: 10, name: "Bielsko-Biała" },
  { id: 11, name: "Białystok" },
  { id: 12, name: "Katowice" },
  { id: 13, name: "Gdynia" },
  { id: 14, name: "Częstochowa" },
  { id: 15, name: "Radom" },
  { id: 16, name: "Zielona Góra" },
  { id: 17, name: "Toruń" },
  { id: 18, name: "Rzeszów" },
  { id: 19, name: "Sosnowiec" },
  { id: 20, name: "Kielce" },
  { id: 21, name: "Gliwice" },
  { id: 22, name: "Olsztyn" },
  { id: 23, name: "Zabrze" },
  { id: 24, name: "Bytom" },
  { id: 25, name: "Rybnik" },
  { id: 26, name: "Ruda Śląska" },
  { id: 27, name: "Tychy" },
  { id: 28, name: "Opole" },
  { id: 29, name: "Gorzów Wielkopolski" },
  { id: 30, name: "Płock" },
  { id: 31, name: "Elbląg" },
  { id: 32, name: "Dąbrowa Górnicza" },
  { id: 33, name: "Wałbrzych" },
  { id: 34, name: "Tarnów" },
  { id: 35, name: "Koszalin" },
  { id: 36, name: "Włocławek" },
  { id: 37, name: "Chorzów" },
  { id: 38, name: "Kalisz" },
  { id: 39, name: "Legnica" },
  { id: 40, name: "Nowy Sącz" },
  { id: 41, name: "Inowrocław" },
  { id: 42, name: "Mysłowice" },
  { id: 43, name: "Ostrowiec Świętokrzyski" },
  { id: 44, name: "Ostrów Wielkopolski" },
  { id: 45, name: "Lubin" },
  { id: 46, name: "Gniezno" },
  { id: 47, name: "Stargard Szczeciński" },
  { id: 48, name: "Głogów" },
  { id: 49, name: "Zamość" },
  { id: 50, name: "Pruszków" },
  { id: 51, name: "Pabianice" },
  { id: 52, name: "Siemianowice Śląskie" },
  { id: 53, name: "Leszno" },
  { id: 54, name: "Ełk" },
  { id: 55, name: "Chełm" },
  { id: 56, name: "Mielec" },
  { id: 57, name: "Tomaszów Mazowiecki" },
  { id: 58, name: "Bełchatów" },
  { id: 59, name: "Tczew" },
  { id: 60, name: "Świdnica" },
  { id: 61, name: "Będzin" },
  { id: 62, name: "Zgierz" },
  { id: 63, name: "Legionowo" },
  { id: 64, name: "Piekary Śląskie" },
  { id: 65, name: "Ostrołęka" },
  { id: 66, name: "Rumia" },
  { id: 67, name: "Starogard Gdański" },
  { id: 68, name: "Starachowice" },
  { id: 69, name: "Wejherowo" },
  { id: 70, name: "Kołobrzeg" },
  { id: 71, name: "Świętochłowice" },
  { id: 72, name: "Dębica" },
  { id: 73, name: "Ząbki" },
  { id: 74, name: "Świdnik" },
  { id: 75, name: "Marki" },
  { id: 76, name: "Mińsk Mazowiecki" },
  { id: 77, name: "Kwidzyn" },
  { id: 78, name: "Chojnice" },
  { id: 79, name: "Zduńska Wola" },
  { id: 80, name: "Nowa Sól" },
  { id: 81, name: "Bolesławiec" },
  { id: 82, name: "Żyrardów" },
  { id: 83, name: "Oświęcim" },
  { id: 84, name: "Malbork" },
  { id: 85, name: "Żary" },
  { id: 86, name: "Sopot" },
  { id: 87, name: "Knurów" },
  { id: 88, name: "Wołomin" },
  { id: 89, name: "Brzeg" },
  { id: 90, name: "Oleśnica" },
  { id: 91, name: "Lębork" },
  { id: 92, name: "Czechowice-Dziedzice" },
  { id: 93, name: "Cieszyn" },
  { id: 94, name: "Sochaczew" },
  { id: 95, name: "Kraśnik" },
  { id: 96, name: "Iława" },
  { id: 97, name: "Oława" },
  { id: 98, name: "Dzierżoniów" },
  { id: 99, name: "Luboń" },
  { id: 100, name: "Ostróda" },
  { id: 101, name: "Pruszcz Gdański" },
  { id: 102, name: "Zgorzelec" },
  { id: 103, name: "Czeladź" },
  { id: 104, name: "Łowicz" },
  { id: 105, name: "Rury" },
  { id: 106, name: "Giżycko" },
  { id: 107, name: "Brodnica" },
  { id: 108, name: "Kętrzyn" },
  { id: 109, name: "Gorlice" },
  { id: 110, name: "Biłgoraj" },
  { id: 111, name: "Kobyłka" },
  { id: 112, name: "Wągrowiec" },
  { id: 113, name: "Turek" },
  { id: 114, name: "Skawina" },
  { id: 115, name: "Kościan" },
  { id: 116, name: "Kościerzyna" },
  { id: 117, name: "Piastów" },
  { id: 118, name: "Bartoszyce" },
  { id: 119, name: "Szczytno" },
  { id: 120, name: "Jawor" },
  { id: 121, name: "Lubartów" },
  { id: 122, name: "Grajewo" },
  { id: 123, name: "Płońsk" },
  { id: 124, name: "Koło" },
  { id: 125, name: "Zambrów" },
  { id: 126, name: "Mrągowo" },
  { id: 127, name: "Działdowo" },
  { id: 128, name: "Sulejówek" },
  { id: 129, name: "Chełmno" },
  { id: 130, name: "Lubań" },
  { id: 131, name: "Chodzież" },
  { id: 132, name: "Złotów" },
  { id: 133, name: "Ozorków" },
  { id: 134, name: "Tomaszów Lubelski" },
  { id: 135, name: "Giszowiec" },
  { id: 136, name: "Łomianki" },
  { id: 137, name: "Jasien" },
  { id: 138, name: "Łańcut" },
  { id: 139, name: "Rawa Mazowiecka" },
  { id: 140, name: "Braniewo" },
  { id: 141, name: "Rypin" },
  { id: 142, name: "Milanówek" },
  { id: 143, name: "Złotoryja" },
  { id: 144, name: "Radzionków Nowy" },
  { id: 145, name: "Osowa" },
  { id: 146, name: "Ustka" },
  { id: 147, name: "Łęczyca" },
  { id: 148, name: "Chełmża" },
  { id: 149, name: "Biały Kamień" },
  { id: 150, name: "Chojnów" },
  { id: 151, name: "Człuchów" },
  { id: 152, name: "Lipno" },
  { id: 153, name: "Słupca" },
  { id: 154, name: "Wąbrzeźno" },
  { id: 155, name: "Sidlice" },
  { id: 156, name: "Golub-Dobrzyń" },
  { id: 157, name: "Aleksandrów Kujawski" },
  { id: 158, name: "Puck" },
  { id: 159, name: "Suchanino" },
  { id: 160, name: "Czarnków" },
  { id: 161, name: "Ksawerów" },
  { id: 162, name: "Wola Rzędzińska" },
  { id: 163, name: "Sejny" },
  { id: 164, name: "Raciąż" },
  { id: 165, name: "Górowo Iławeckie" },
  { id: 166, name: "Zgłobice" },
  { id: 167, name: "Libertów" },
  { id: 168, name: "Zbylitowska Góra" },
  { id: 169, name: "Wiśniowa Góra" },
  { id: 170, name: "Koszyce" },
  { id: 171, name: "Latoszyn" },
  { id: 172, name: "Jodłówka" },
];
