from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

driver = webdriver.Firefox()

driver.get("https://iaff.nocservice.biz/accommodation")

destination_input = driver.find_element(By.XPATH, '//*[@id="destination_input"]')
city_choice = driver.find_element(By.XPATH, '//*[@id="city_dropdown"]/li[1]')
check_in_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div/div/input')
check_out_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/div/div/input')
guest_input = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[1]/div[3]/div[1]/input')
room_input = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[1]/div[3]/div[2]/input')
price_category_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[1]/button')
price_choice_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[1]/div/div/div[2]/label/input')
filters_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[2]/button')
filters_choice_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[2]/div/div/div[1]/label/input')
sort_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[3]/button')
sort_choice_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[3]/div/div/div[4]/label/input')
search_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[2]/div/div[2]/div[4]/button')
first_choice_button = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/div[3]/div/div[2]/div[2]/button')

destination_input.sendKeys("Warsaw")
time.sleep(2)
select = Select(dropdown)
select.select_by_visible_text("Warsaw")
time.sleep(1)
check_in_button.click()
time.sleep(1)
check_out_button.click()
time.sleep(1)
guest_input.click()
time.sleep(1)
room_input.click()
time.sleep(1)
price_category_button.click()
time.sleep(1)
price_choice_button.click()
time.sleep(1)
filters_button.click()
time.sleep(1)
filters_choice_button.click()
time.sleep(1)
sort_button.click()
time.sleep(1)
sort_choice_button.click()
time.sleep(1)
search_button.click()
time.sleep(1)
first_choice_button.click()
time.sleep(1)

driver.quit()
